### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by JanSzyndlarewicz** [JanSzyndlarewicz/Smart-Home#22]
- [x]  Początkowe okienko do wyboru (rejestracja/login) (GUI)

- [x]  Okno do rejestracji (GUI)

- [x]  Podpiąć prawy panel do urządzeń, działa zmiana danych za pomocą sliderów, toggle itp (GUI)

- [x]  Brak możliwości otwierania więcej niż jednego okna danego typu

- [x]  Dodanie nowych typów rutyn (BE)

- [x]  Dodać panele do dodawania lokacji, rutyn i usuwania rutyn(JUŻ PRZETESTOWANE I PODPIĘTE DO KONTROLERA) (GUI)

- [x]  Metody rejestrujące rutyny Controller -> BackEnd (BE)

- [x]  Przekazywanie zmian dokonanych za pomocą DevicePanel GUI <-> Controller (GUI)

- [x]  Przekazywanie zmian dokonanych w tle BackEnd <-> Controller (BE)

- [x]  Zaimplementowanie serializacji (Na koniec) (GUI)

- [x] Dodanie sposobu na debugowe sterowanie sensorami

**Comment by therockey** [comment]
można dodawać rutyny

**Comment by therockey** [comment]
jest progres

**Comment by therockey** [comment]
jebać ten kontroler już
